### ISSUE TITLE
The annual worldwide programming competition 'The Facebook Hacker Cup' .

### ISSUE THREAD

**Issue by saurabhjn76** [iiitv/ShareIt#17]
In the Hacker Cup, programmers from around the world will be judged on accuracy and speed as they race to solve algorithmic problems to advance through up to five rounds of programming challenges. A chance to compete against the world’s best programmers for awesome prizes and the title of World Champion.
The qualification round will begin on Jan 06,2017.
Get into the Hacker Cup by registering here: http://www.facebook.com/hackercup/register

**Comment by singhpratyush** [comment]
Is it compulsory to have a Facebook account to register for the event?

**Comment by saurabhjn76** [comment]
Yes, you need to have a Facebook account.
