### ISSUE TITLE
Google APAC 2017 University Test

### ISSUE THREAD

**Issue by saurabhjn76** [iiitv/ShareIt#9]
Have a look at:
https://code.google.com/codejam/apactest

**Comment by aviaryan** [comment]
Thanks for sharing .

> Calling all university students interested in a career at Google: it's time to register and start practicing for the Google APAC 2017 University Test! This year, we have opened the contest to all students enrolled in higher education institutions in the APAC region.

**Comment by saurabhjn76** [comment]
What is the University ID for IIITV ?

**Comment by 7ranveer** [comment]
your college id , according to answers on stackoverflow and quora.
https://www.quora.com/What-should-we-put-in-the-University-ID-column-while-registering-for-the-Google-Apac-2016-test

**Comment by 7ranveer** [comment]
please use your college mail id to register.
